name: Test Custom Action
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Запуск нашего экшена
        uses: ./.github/actions/hello-world