name: Unity Build

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Unity
      uses: game-ci/unity-action@v2
      with:
        unityVersion: 2021.3.18f1  # Укажите вашу версию Unity
        activateLicense: false  # (необязательно) Для активации лицензии

    - name: Prepare build script
      run: |
        chmod +x ./build/build.bat  # Даем права на выполнение скрипту

    - name: Build the project
      run: |
        ./build/build.bat  # Запуск bat скрипта для сборки проекта на Windows

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: unity-build
        path: ./Builds
