name: Unity Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Unity using Docker
      run: |
        docker run --rm \
        -v ${{ github.workspace }}:/project \
        unityci/editor:2021.3.18f1 \
        /bin/bash -c "cd /project && /opt/Unity/Editor/Unity -batchmode -nographics -quit -projectPath /project -buildTarget StandaloneWindows64 -executeMethod BuildScript.PerformBuild"

