name: Unity Build

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # или windows-latest в зависимости от вашего окружения

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Unity
      uses: game-ci/unity-action@v2
      with:
        unityVersion: 2021.3.18f1  # Укажите вашу версию Unity
        activateLicense: true  # (необязательно) Для активации лицензии

    - name: Build the project
      run: |
        # Выполнение команды сборки
        ./build.sh  # или ваша команда сборки, например через Unity CLI

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: unity-build
        path: ./Builds