name: Unity Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Cache Library
      uses: actions/cache@v3
      with:
        path: Library
        key: Library-${{ runner.os }}-${{ github.sha }}
        restore-keys: |
          Library-${{ runner.os }}-

    - name: Activate Unity License
      run: echo "${{ secrets.UNITY_LICENSE }}" > Unity_lic.ulf

    - name: Build the Unity project
      uses: game-ci/unity-builder@v4
      with:
        unityVersion: 2021.3.18f1  # Версия Unity, соответствующая вашему проекту
        targetPlatform: StandaloneWindows64  # Можно изменить на WebGL, Android и т. д.

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: unity-build
        path: Build/


