name: Unity Build and Test

on:
  push:
    branches:
      - main  # Запуск при пуше в main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  # Клонируем репозиторий

      - name: Install Unity
        uses: game-ci/unity-setup@v2  # Устанавливаем Unity
        with:
          unityVersion: 2021.3.18f1  # Версия Unity
          activateLicense: true
          unityLicenseFile: ${{ secrets.UNITY_LICENSE }}  # Лицензия Unity (.ufl)

      - name: Run Tests with Unity Test Runner
        uses: game-ci/unity-test-runner@v4  # Запуск тестов
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}  # Лицензия
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}  # Почта Unity
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}  # Пароль Unity
        with:
          projectPath: path/to/your/project  # Путь к проекту в репозитории
          githubToken: ${{ secrets.GITHUB_TOKEN }}  # Используем GitHub токен для CI/CD

      - name: Upload Test Results
        uses: actions/upload-artifact@v3  # Загружаем результаты тестов
        with:
          name: TestResults
          path: path/to/test-results  # Путь к результатам тестирования