name: Build and Test Project

on: [push, pull_request]

permissions:
  contents: read
  actions: read
  checks: write  # Для публикации результатов тестов
  pull-requests: write  # Если тесты связаны с PR

jobs:
    test:
        name: Run Tests
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - name: Run Unity Tests
              uses: game-ci/unity-test-runner@v4
              env:
                  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
                  UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
                  UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
              with:
                  projectPath: .
                  githubToken: ${{ secrets.GITHUB_TOKEN }}  # Добавлен токен

    build:
        needs: test  # Сборка начнется только если тесты успешны
        name: Build for ${{ matrix.targetPlatform }}
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                targetPlatform:
                    - StandaloneWindows64
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
                  lfs: true
            - uses: actions/cache@v3
              with:
                  path: Library
                  key: Library-${{ matrix.targetPlatform }}
                  restore-keys: Library-
            - uses: game-ci/unity-builder@v2
              env:
                  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
              with:
                  targetPlatform: ${{ matrix.targetPlatform }}
                  githubToken: ${{ secrets.GITHUB_TOKEN }}  # Добавлен токен
            - uses: actions/upload-artifact@v4
              with:
                  name: Build-${{ matrix.targetPlatform }}
                  path: build/${{ matrix.targetPlatform }}
   